### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'PlayerProvider')

### ISSUE THREAD

**Issue by elibenton** [JosueRhea/headless-audioplayer#2]
Hi there! Thanks for making this nice package.

When trying to follow the example setup for SvelteKit`1.5.0`, I get the following error that I don't know how to resolve.

```
TypeError: Cannot read properties of undefined (reading 'PlayerProvider')
    at eval (/src/routes/+page.svelte:17:75)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.default (root.svelte:42:40)
    at eval (/node_modules/@sveltejs/kit/src/runtime/components/layout.svelte:8:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at root.svelte:41:39
    at $$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1900:26)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:180:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I am using Typescript, but am unfamiliar with it. Do I need to explicitly define the types for `headless-audioplayer` somewhere? Does that package already do that?

**Comment by JosueRhea** [comment]
Hey, it's JosueRhea here.

Thank you for reporting the issue, and I'm sorry that I'm probably too late to fix the problem.

However, I have fixed the problem in version 1.0.2, which I just released. It was just a missing export that Svelte-Kit apparently requires for its packages.

> *I am using TypeScript, but I am unfamiliar with it. Do I need to explicitly define the types for headless-audioplayer somewhere? Does that package already do that?*

The answer to that is no. The package is typed by default, so you don't need to define the types.

You have to make sure that you put your player component into a separate file because the PlayerProvider is a context. To access that context, you have to create a component and wrap the component with the PlayerProvider, just as the example shows.
